### ISSUE TITLE
Console: Break services down into super-groups

### ISSUE THREAD

**Issue by rbren** [kaltura/kaltura-api-recipes#10]

**Comment by rbren** [comment]
@zoharbabin This UI is ready, just need the actual groups.

**Comment by zoharbabin** [comment]
@bobby-brennan  - please see attached pdf for the groups.
Note the following:
1. In some cases, we need specific actions to be under the group (e.g. baseEntry.list under search or the object.bulkX actions under bulk ingest). So it's not always services under the group, sometimes it's more granular as an action.
2. Those marked with (deprecated) and (hidden) should be hidden from the UI by default. And add a URL parameter hidden=false that will unhinde them. This should also be applied to all actions marked as deprecated in the schema.

[kaltura-api-groups.pdf](https://github.com/kaltura/kaltura-api-recipes/files/177836/kaltura-api-groups.pdf)

Let me know if you'd like to discuss over a call.

**Comment by rbren** [comment]
Thanks Zohar, will implement today.

I don't see any actions marked deprecated in [api_schema.php](http://www.kaltura.com/api_v3/api_schema.php) - is there a specific field I should look for?

**Comment by jessp01** [comment]
Hi Bobby,

This info is in the doxygen blocks in the code, for example:
https://github.com/kaltura/server/blob/Kajam-11.11.0/api_v3/services/UploadService.php#L8
`@deprecated Please use UploadToken service`

@tan-tan-kanarek - it indeed seems like that info does not make it into the schema. Can you confirm? The thing is the LucyBot app relies on the schema for retrieving all the metadata as far as services, actions, enums, etc goes and also relies on that to generate documentation, so, we need some indication for that in shcema.

Thanks,

**Comment by rbren** [comment]
Another question - Jess, the api_schema.xml you e-mailed me seems to be
missing certain services, e.g. drmProfile.

I'm using this as a source of truth (Generated on date 18/02/16 11:39:10):
https://github.com/bobby-brennan/kaltura-schema/blob/master/api_schema.xml

drmProfile is in http://www.kaltura.com/api_v3/api_schema.php though

Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
Hi Bobby,

Yes, that is because our generator takes under consideration what plugins 
have been enabled in /opt/kaltura/app/configurations/plugins.ini, the 
default for which is:
https://github.com/kaltura/server/blob/Kajam-11.11.0/configurations/plugins.template.ini

I just pushed a new schema version here:
https://github.com/kaltura/kaltura-api-recipes/blob/lucy-api-portal/api_schema.xml

Generated after enabling all plugins.

Thanks,

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by rbren** [comment]
Thanks Jess! The plugins should all be there now.
