### ISSUE TITLE
Add Step Wizard Progress Navigation Instead of the Steps DropDown

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/kaltura-api-recipes#14]
Will make the recipes look more like a step by step training wizard.
Example reference; http://codepen.io/timshingyu/pen/QbqbxO

**Comment by rbren** [comment]
Devin and I talked about this and we're not convinced it's a good idea. Two
issues:
- there's no way to see the title of a step before clicking on it
- the UI is not scalable to recipes with e.g. 10 steps

What do you think?

**Comment by zoharbabin** [comment]
I agree.
