### ISSUE TITLE
Investigate missing partnerID

### ISSUE THREAD

**Issue by rbren** [kaltura/kaltura-api-recipes#17]
From Zohar:

Not all accounts I have access to are actually loaded into the chosen dropbox during login. See attached image for reference. The account name I was looking for is "SAP Media Share” pid=1921661. I have access to this account under zohar.babin@kaltura.com and I can see it in the KMC’s switch account menu, but I don’t see it in the recipes login menu.

Here's the code for getting pids:

``` js
var kaltura_conf = new kc.KalturaConfiguration(req.body.partnerId);
  var client = new kc.KalturaClient(kaltura_conf);
  var type = ktypes.KalturaSessionType.ADMIN;
  client.user.loginByLoginId(function(ks) {
    if (!ks) return res.send("Error logging in");
    client.setKs(ks);
    client.partner.listPartnersForUser(function(partners) {
      res.json(partners.objects);
    })
  }, req.body.email, req.body.password)
```

**Comment by jessp01** [comment]
Should be fixed with: https://github.com/kaltura/kaltura-api-recipes/commit/b49392576884adb804751cd9a6d56a2e9fd62631

@zoharbabin - I deployed it on developer.kaltura.org please try and let me know.

Thanks,

**Comment by zoharbabin** [comment]
@jessp01 - wonderful, seems to work well. thanks!

@bobby-brennan / @jessp01 - can you please make the account selection drop-down a [chosen](https://harvesthq.github.io/chosen/) drop-down so one could search?

Thanks!

**Comment by rbren** [comment]
Done.
