### ISSUE TITLE
Make ENUM selectors as drop-down instead of select-box

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/kaltura-api-recipes#20]
![format-drop-down](https://cloud.githubusercontent.com/assets/150514/13553499/8d2fdcde-e394-11e5-8b58-c8be6f0ced6e.png)

**Comment by rbren** [comment]
Agreed this looks better, done

**Comment by jessp01** [comment]
Hi Bobby,

Deployed latest and still don't see the selectboxes. Where is this fix made? I suppose
$ git pull
$ npm install
is just not enough?

**Comment by rbren** [comment]
You might have been too quick for me :)

Can you try again? Everything should be pushed

Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
Sorry Bobby, still seeing radio buttons..

Got this as the last commit: 0f772e4bd82e753669c59ed5ee34c2d4b3202cac

Also still seeing '/' escaped as "%252F''

**Comment by rbren** [comment]
Can you rm -rf node_modules && npm install ?

Bobby Brennan
bobby.brennan@gmail.com

**Comment by jessp01** [comment]
Works fine now.
