### ISSUE TITLE
Filters and pagers are missing from some of the API actions

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/kaltura-api-recipes#21]
Filters and Pagers are missing from some of the actions. See example (service/media/action/get):
![filter-pager](https://cloud.githubusercontent.com/assets/150514/13553503/a7c92816-e394-11e5-9062-45e653e89a56.png)

**Comment by rbren** [comment]
IIUC media.get shouldn't have a filter or pager - it just gets a single item.  media.list does have the filter/pager.

**Comment by jessp01** [comment]
Hi Bobby,

Yes, get() has no filter or pager cause it gets one ID. We are talking about list()

About list, there are two issues:
0. indeed we want to clear up space in the form and make it simpler. i.e, not showing all filter options from the get go as they are not mandatory.
1. Things like advancedSearch (KalturaSearchItem) do not show up.

In the schema, they exist like so:

```
<class name="KalturaSearchItem" abstract="1" description=""/>
```

And then, you need to find all classes to which KalturaSearchItem is base.

This opens up multiple options as you can see in http://www.kaltura.com/api_v3/testme/
if you choose for example "media" as service, "list" as action and then click "edit" above "filter (KalturaMediaEntryFilter)", you will see "advancedSearch (KalturaSearchItem)" and multiple types to select from. So, we need to properly parse the schema XML to include that and then think of how best to represent it graphically.

**Comment by rbren** [comment]
Are you talking about this issue?

[API input Objects should be represented with windows rather than many open fields](https://github.com/kaltura/kaltura-api-recipes/issues/22)

See the screenshot there - maybe we could make each nested parameter collapsed by default?  Will work on getting in the deeply-nested parameters like advancedSearch

**Comment by zoharbabin** [comment]
true, my bad. closing as duplicate.
