### ISSUE TITLE
In the media.list API console the player is not rendering in the Visual box

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/kaltura-api-recipes#23]
![media-list-player-not-rendering](https://cloud.githubusercontent.com/assets/150514/13553549/079e7d80-e396-11e5-9bbb-f3d7dbe248a1.png)

**Comment by zoharbabin** [comment]
@bobby-brennan  - is this going to change with v2 as well?

**Comment by rbren** [comment]
All that needs to be done here is pick a default UI conf for the user. Will fix shortly

**Comment by zoharbabin** [comment]
ok.. please ensure that it choses a v2 player from the logged-in account.

**Comment by rbren** [comment]
The player should be showing up now, but it's just using the first result from uiConf.list - how do I detect whether it's a "v2" player?

**Comment by jessp01** [comment]
"class": "KalturaUiConfFilter",
     "parameters": {
    "objTypeIn": {
        "enum": "KalturaUiConfObjType",
        "value": "PLAYER_V3"
    },
     }

Should probably be enough.

May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]
