### ISSUE TITLE
Dedicated page for every service/action 

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/kaltura-api-recipes#24]
When you want to share a specific action or service with someone, ideally you would send a URL somewhat like: https://cookbook.kaltura.com/console#/Documentation/service/media/action/get .
That URL will take you to a page that only has this service/action and a button/link to go back to the rest of the documentation.

That will also allow us to add Disquss comments below each service/action to encourage community discussion (Similar to: http://php.net/manual/en/function.strstr.php ).

**Comment by rbren** [comment]
The example you gave uses a URL fragment, which is already supported, e.g.

https://developer.kaltura.org/console#/Documentation/get/%252Fservice%252Fmedia%252Faction%252Fget

What's the end goal here? Maybe we could add a Discussion tab?

**Comment by jessp01** [comment]
Hey Bobby,

Yes, that does take you to the right place but I'm not sure why the "/" suddenly needs encoding? referring to the "%252F"

We want something similar to what php.net has, I suppose it could be done in a separate discussion tab, that's more of a UX thing and less my area. Zohar?

**Comment by rbren** [comment]
Looks like I was being overly cautious :)  I got rid of the encoding so now the links will look like this:

developer.kaltura.org/console#/Documentation/GET/service/media/action/list

**Comment by zoharbabin** [comment]
Two requests here:
1. I want to be able to share specific action or service pages, where the focus and context to the person opening the URL will be very clearly on that specific API service or action shared.
   Should be done by creating a dedicated view where nothing else is shown but this specific service or action (e.g. no side menu, no other services and actions shown on the page, etc.). I'm fine with all these being hidden using JavaScript and have a button to un-hide. 
   The important thing is that context is clear and there's nothing else on the page.
2. Once we have the above, adding embedded comment threads from https://forum.kaltura.org . Essentially, each page would have its own assigned forum thread, and that way all comments belong to that specific thread.

**Comment by rbren** [comment]
I added "discussion" pages for each operation at /discussion/service/{service}/action/{action}.  Right now it just has the operation title and description, with links to recipes, docs, and API console (see screenshot).

Are you guys able to handle linking this to forum.kaltura.org? @jessp01 FYI everything is done in these files:
routes/discussion.js
views/discussion.jade
static/css/discussion.css

![screen shot 2016-03-07 at 3 51 37 pm](https://cloud.githubusercontent.com/assets/7611973/13582895/b79e57fa-e47c-11e5-8d46-3b0e575f0363.png)
