### ISSUE TITLE
recipes/analytics#/step2 - reportType selection from the UI is incorrectly interpreted

### ISSUE THREAD

**Issue by jessp01** [kaltura/kaltura-api-recipes#63]
To reproduce, go to https://developer.kaltura.com/recipes/analytics#/step2 and select a different report type, you will see the code changes to a type different than the chosen one.
For example, when choosing 'TOP_CREATORS', the code changes to:
var reportType = Kaltura.kc.enums.KalturaReportType.BROWSERS;
and if you look at the actual API call that goes out, it too will have the wrong value:
https://www.kaltura.com/api_v3/service/report/action/getTotal?format=1&reportType=23&reportInputFilter[fromDay]=20160101&reportInputFilter[toDay]=20161001&ks=

The important part being:

```
reportType=23
```

Which is the value for the BROWSERS enum, not the TOP_CREATORS one.

**Comment by jessp01** [comment]
Also, for this to be useful, the API action should be getTable(), not getTotal(), which will return the same thing no matter what reportType you choose.

**Comment by rbren** [comment]
Thanks for the report - looks like the enums were getting mislabeled after the schema refresh.  Should be fixed now.

**Comment by jessp01** [comment]
Thanks, Bobby, combined with my last commit:
https://github.com/kaltura/kaltura-api-recipes/commit/e080fb97abd49a0fcfc9a55810b35a7d6061eac8

This can be closed.
